import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { runDeterministicAudit } from './auditEngine.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
app.use(cors());
app.use(express.json());

// USP #2: Dodo Payments Auto-Freeze Action
export function triggerDodoPayoutHold(vendorName, invoiceNum, amountHeld) {
  return {
    payout_status: "FROZEN",
    provider: "Dodo Payments",
    transaction_ref: `DODO-HLD-${Date.now()}`,
    vendor: vendorName,
    invoice_target: invoiceNum,
    held_amount: amountHeld,
    action_note: "Discrepancy detected by LedgerGuard agent. Automated payout withheld pending dispute resolution.",
    timestamp: new Date().toISOString()
  };
}

// USP #3: Neatlogs Decision Tracing Integration
export function logToNeatlogs(traceItem) {
  console.log(`[NEATLOGS TRACE - ${traceItem.timestamp}] [${traceItem.step}]:`, traceItem);
  return { logged: true, sink: "Neatlogs-Observability" };
}

// USP #4: Autonomous Dispute Dossier Generator
export function generateDisputeDraft(invoice, auditResult) {
  const discrepancyList = auditResult.discrepancies
    .map((d, i) => `${i + 1}. [${d.type}] ${d.details}`)
    .join("\n");

  return `ATTENTION: Accounts Payable & Vendor Relations
RE: Formal Dispute Notice - Invoice ${invoice.invoice_number} (Ref: ${invoice.po_reference})
Vendor: ${invoice.vendor_name}

Dear Finance Team,

Our autonomous audit system (LedgerGuard) has flagged the following discrepancies against authorized Purchase Order ${invoice.po_reference}:

${discrepancyList}

ACTION TAKEN:
- Automated payout of $${invoice.claimed_grand_total} via Dodo Payments has been placed on ADMINISTRATIVE HOLD.
- Please issue a corrected credit memo and revised invoice reflecting the contracted unit rates and taxes.

Generated by LedgerGuard Autonomous CFO Agent Fleet.`;
}

// Main Audit Route
app.post('/api/audit', (req, res) => {
  const { po, invoice } = req.body;

  if (!po || !invoice) {
    return res.status(400).json({ error: "Both PO and Invoice payloads are required." });
  }

  const auditResult = runDeterministicAudit(po, invoice);
  auditResult.traces.forEach(trace => logToNeatlogs(trace));

  let dodoAction = null;
  let disputeEmail = null;

  if (!auditResult.is_valid) {
    dodoAction = triggerDodoPayoutHold(invoice.vendor_name, invoice.invoice_number, invoice.claimed_grand_total);
    disputeEmail = generateDisputeDraft(invoice, auditResult);
  }

  return res.json({
    success: true,
    audit_summary: {
      is_clean: auditResult.is_valid,
      risk_score: auditResult.risk_score,
      total_discrepancies: auditResult.discrepancies.length
    },
    discrepancies: auditResult.discrepancies,
    dodo_payments_hold: dodoAction,
    neatlogs_traces: auditResult.traces,
    dispute_email_draft: disputeEmail
  });
});

// Demo Verification Endpoint - Fraud Case
app.get('/api/demo-run', (req, res) => {
  try {
    const poPath = path.join(__dirname, '../mock-data/po_101.json');
    const invPath = path.join(__dirname, '../mock-data/invoice_fraud_101.json');

    const po = JSON.parse(fs.readFileSync(poPath, 'utf8'));
    const invoice = JSON.parse(fs.readFileSync(invPath, 'utf8'));

    const auditResult = runDeterministicAudit(po, invoice);
    const dodoAction = triggerDodoPayoutHold(invoice.vendor_name, invoice.invoice_number, invoice.claimed_grand_total);
    const disputeEmail = generateDisputeDraft(invoice, auditResult);

    return res.json({
      demo_status: "LIVE_FRAUD_CAUGHT",
      po_analyzed: po.po_number,
      invoice_analyzed: invoice.invoice_number,
      auditResult,
      dodoAction,
      disputeEmail
    });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

// Demo Verification Endpoint - Clean Case
app.get('/api/demo-clean', (req, res) => {
  try {
    const poPath = path.join(__dirname, '../mock-data/po_101.json');
    const invPath = path.join(__dirname, '../mock-data/invoice_clean_101.json');

    const po = JSON.parse(fs.readFileSync(poPath, 'utf8'));
    const invoice = JSON.parse(fs.readFileSync(invPath, 'utf8'));

    const auditResult = runDeterministicAudit(po, invoice);

    return res.json({
      demo_status: "PASSED_VERIFIED",
      po_analyzed: po.po_number,
      invoice_analyzed: invoice.invoice_number,
      auditResult,
      dodoAction: {
        payout_status: "AUTO_APPROVED",
        provider: "Dodo Payments",
        transaction_ref: `DODO-TXN-${Date.now()}`,
        released_amount: invoice.claimed_grand_total,
        action_note: "Clean 3-way match. Automated payout released without CFO intervention.",
        timestamp: new Date().toISOString()
      },
      disputeEmail: null
    });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

// Grounded Contract Rules (Deterministic Fallback Guardrails)
const CONTRACT_RULES = [
  {
    keywords: ["inflation", "market rate", "raw material", "price hike", "mehenga"],
    reply: "As per Master Agreement (Clause 4.2), all unit pricing remains locked for the active fiscal term. Upward rate revisions require a minimum 30-day prior written notice and formal addendum. The unauthorized surcharge is rejected.",
    action: "DISPUTE_UPHELD",
    clause: "Clause 4.2 - Price Lock Guarantee"
  },
  {
    keywords: ["shipping", "freight", "delivery", "urgent", "express"],
    reply: "PO-2026-101 explicitly includes standard DDP logistics. Section 8.1 forbids expedited freight markups unless authenticated by a dual-signed Operations Token.",
    action: "EVIDENCE_REQUIRED",
    clause: "Section 8.1 - Logistics Surcharge Policy"
  },
  {
    keywords: ["mistake", "typo", "sorry", "error", "clerical"],
    reply: "Discrepancy acknowledged. Please transmit a formal Credit Memo and issue corrected revised invoice. The Dodo Payments hold will release automatically upon clean reconciliation.",
    action: "AWAITING_CREDIT_MEMO",
    clause: "Resolution Protocol - Credit Note Remediation"
  },
  {
    keywords: ["stop delivery", "truck", "cancel", "hold supply", "roka"],
    reply: "Threat of supply disruption constitutes a material breach of Master Service Agreement (Clause 14 - Continuous Supply Assurance). Incident flagged and automatically escalated to Legal & CFO.",
    action: "ESCALATED_LEGAL",
    clause: "Clause 14 - Supply Continuity Breach"
  }
];

// Unified Autonomous Negotiation Agent (TensorMux LLM + Contract Guardrails)
app.post('/api/negotiate', async (req, res) => {
  const { vendorMessage, auditSummary } = req.body;

  if (!vendorMessage) {
    return res.status(400).json({ error: "Message is required." });
  }

  // 1. Live TensorMux LLM Inference (glm-4-7-flash)
  if (process.env.TENSORMUX_API_KEY) {
    try {
      const response = await fetch(`${process.env.TENSORMUX_BASE_URL}/chat/completions`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${process.env.TENSORMUX_API_KEY}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          model: process.env.TENSORMUX_MODEL || 'glm-4-7-flash',
          messages: [
            {
              role: 'system',
              content: `You are LedgerGuard Autonomous CFO Agent representing corporate spend compliance.
Audit Findings: ${JSON.stringify(auditSummary || { note: "PO and invoice discrepancies found" })}.
Contract Rules:
- Locked fiscal unit pricing (Clause 4.2). Unapproved price hikes are strictly rejected.
- Logistics included in PO (Section 8.1). Expedited fees need signed operations token.
- Typo/error requires a revised invoice and Credit Memo.
- Threats of supply stoppage breach Clause 14 (Continuous Supply Assurance).
Keep response professional, firm, concise (under 80 words), and cite relevant contract clauses. Dodo Payments hold remains active.`
            },
            { role: 'user', content: vendorMessage }
          ],
          temperature: 0.3,
          max_tokens: 1024
        })
      });

      const data = await response.json();
      const choice = data.choices?.[0]?.message;
      const rawText = choice?.content || choice?.reasoning;

      if (rawText) {
        return res.json({
          success: true,
          source: "TensorMux glm-4-7-flash",
          agent_reply: rawText,
          agentReply: rawText, // compatibility fallback for UI
          dodo_hold: "RETAINED",
          timestamp: new Date().toISOString()
        });
      }
    } catch (err) {
      console.error("[TENSORMUX ERROR - Triggering Fallback]:", err.message);
    }
  }

  // 2. Deterministic Fallback Engine
  const cleanText = vendorMessage.toLowerCase();
  const match = CONTRACT_RULES.find(rule => rule.keywords.some(kw => cleanText.includes(kw)));

  const fallbackReply = match 
    ? match.reply 
    : "Your statement has been logged into the audit record. However, invoices must reconcile strictly with authorized Purchase Order lines. Dodo Payments hold remains active pending certified proof of approval.";

  return res.json({
    success: true,
    source: "Contract Rule Fallback",
    agent_reply: fallbackReply,
    agentReply: fallbackReply,
    applied_clause: match ? match.clause : "Standard Reconciliation Mandate",
    dispute_status: match ? match.action : "UNDER_REVIEW",
    dodo_hold: "RETAINED",
    timestamp: new Date().toISOString()
  });
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(`\n======================================================`);
  console.log(` LedgerGuard CFO Audit Engine running on Port ${PORT}`);
  console.log(` Mode: Pure ES6 Modules`);
  console.log(` Dodo Payments, Neatlogs & TensorMux initialized.`);
  console.log(`======================================================\n`);
});